name: Setup Node.js and Install Dependencies
description: Checks out the repository, installs pnpm and Node.js, then installs dependencies.

inputs:
  node-version-file:
    description: Path to the Node.js version file.
    required: false
    default: .nvmrc
  install-args:
    description: Arguments to pass to pnpm install.
    required: false
    default: --frozen-lockfile
  with-pnpm-cache:
    description: Enable pnpm cache via setup-node.
    required: false
    default: "pnpm"

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup pnpm
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

    - name: Setup Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: ${{ inputs.with-pnpm-cache }}

    - name: Install dependencies
      run: pnpm install ${{ inputs.install-args }}
      shell: bash
